### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by unixorn** [saims0n/Zsh-Theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I only add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

The plugin's name is very generic. Please consider renaming it to something descriptive, or even just name it after your github username.

Finally, don't take these as criticisms of the work you've done, they're meant to make a more useful entry in the plugin/theme list.

Thanks!

**Comment by saims0n** [comment]
Thank you man i'll make changes for sure.

**Comment by saims0n** [comment]
![Screenshot from 2021-02-26 19-52-47](https://user-images.githubusercontent.com/53370662/109313133-e0031980-786d-11eb-96a3-fde11296a43a.png)
![Screenshot from 2021-02-26 19-55-37](https://user-images.githubusercontent.com/53370662/109313140-e2657380-786d-11eb-944d-ed3bf8604e90.png)

**Comment by saims0n** [comment]
![Screenshot from 2021-02-26 20-11-40](https://user-images.githubusercontent.com/53370662/109314121-f78ed200-786e-11eb-8a4c-db922e2d4ff2.png)

**Comment by unixorn** [comment]
I recommend renaming the repository to 14degree as well. Otherwise everything looks good.

**Comment by saims0n** [comment]
Sir Please add my theme in zsh.
